# Generated by Django 4.2.5 on 2023-09-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_author_post_postauthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='commentRating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='postRating',
        ),
    ]
